{% set name = "nhs-number" %}
{% set version = "1.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nhs_number-{{ version }}.tar.gz
  sha256: f93ba884395bdba2ab7e8b9162b3861ce8fcca6db9709971eba5b785fa276ed2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - nhs_number
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andylaw/NhsNumberChecks
  summary: Python library for checking the validity of NHS Numbers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andylaw
